# Generated by Django 5.2.6 on 2026-04-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships_app', '0003_application_is_paid_scholarship_application_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='match_score_at_application',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interested_field',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='DocumentVault',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
