# Generated by Django 5.2.6 on 2026-05-01 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships_app', '0004_remove_notification_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_premium',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='country',
            new_name='field',
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='scholarship',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='success',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='application_fee',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='apply_link',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='image',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='required_gpa',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='scholarship_type',
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='vault/cvs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='vault/transcripts/'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='min_gpa',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Under Review', 'Under Review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Under Review', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interested_field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_paid',
        ),
    ]
